"""add inventory_transactions table

Revision ID: 63ef1338b372
Revises: 
Create Date: 2026-03-09 08:38:54.567472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63ef1338b372'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_product_rating',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('v_products_effective_price',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('short_desc', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_start', sa.DateTime(), nullable=True),
    sa.Column('sale_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('effective_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', 'ADJUST', name='transaction_type_enum'), nullable=False),
    sa.Column('reference_type', sa.Enum('ORDER', 'PURCHASE', 'RETURN', 'MANUAL', name='reference_type_enum'), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('quantity_changed', sa.Integer(), nullable=False),
    sa.Column('qty_after_transaction', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shipping_rates')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_cat_parent'))
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'])
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=mysql.ENUM('placed', 'payment_confirmed', 'admin_confirmed', 'shipping_started', 'delivered', 'completed', 'cancelled', 'restocked', 'mock_paid', 'confirmed', 'fulfilled', 'paid', 'momo_paid', 'vnpay_paid'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_oe_order'))
        batch_op.drop_constraint(batch_op.f('order_events_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_oi_order'))
        batch_op.drop_index(batch_op.f('idx_oi_product'))
        batch_op.drop_constraint(batch_op.f('fk_oi_order'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('COD', 'BANK_TRANSFER', 'MOCK_TRANSFER'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'COD'"))
        batch_op.alter_column('payment_status',
               existing_type=mysql.ENUM('unpaid', 'paid', 'transfer_confirmed', 'mock_paid'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'unpaid'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending_payment', 'waiting_admin_confirmation', 'shipping', 'delivered', 'completed', 'cancelled', 'pending', 'confirmed', 'fulfilled'),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_payment'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_orders_status_time'))
        batch_op.drop_index(batch_op.f('idx_orders_vnpay_txn_ref'))

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pc_cat'))
        batch_op.drop_constraint(batch_op.f('fk_pc_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_pc_category'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_pi_prod_sort'))
        batch_op.drop_constraint(batch_op.f('fk_pi_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_reviews_prod_time'))
        batch_op.drop_constraint(batch_op.f('fk_reviews_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('product_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stock_qty'))
        batch_op.drop_constraint(batch_op.f('fk_stock_product'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('publish_year',
               existing_type=mysql.YEAR(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('age_min',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('age_max',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_products_active'))
        batch_op.drop_index(batch_op.f('idx_products_created'))
        batch_op.drop_index(batch_op.f('idx_products_slug'))
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ur_role'))
        batch_op.drop_constraint(batch_op.f('fk_ur_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_users_active'))
        batch_op.drop_index(batch_op.f('idx_users_created'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('idx_users_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ur_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_ur_role'), ['role_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_products_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('age_max',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('age_min',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('publish_year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(display_width=4),
               existing_nullable=True)

    with op.batch_alter_table('product_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_product'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_stock_qty'), ['qty_on_hand'], unique=False)

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_product'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_reviews_prod_time'), ['product_id', 'created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('rating',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pi_product'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_pi_prod_sort'), ['product_id', 'sort_order'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pc_category'), 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_pc_product'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_pc_cat'), ['category_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_orders_vnpay_txn_ref'), ['vnpay_txn_ref'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_status_time'), ['status', 'created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('pending_payment', 'waiting_admin_confirmation', 'shipping', 'delivered', 'completed', 'cancelled', 'pending', 'confirmed', 'fulfilled'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_payment'"))
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('unpaid', 'paid', 'transfer_confirmed', 'mock_paid'),
               existing_nullable=False,
               existing_server_default=sa.text("'unpaid'"))
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('COD', 'BANK_TRANSFER', 'MOCK_TRANSFER'),
               existing_nullable=False,
               existing_server_default=sa.text("'COD'"))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_oi_order'), 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_oi_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_oi_order'), ['order_id'], unique=False)

    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_events_ibfk_1'), 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_oe_order'), ['order_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('placed', 'payment_confirmed', 'admin_confirmed', 'shipping_started', 'delivered', 'completed', 'cancelled', 'restocked', 'mock_paid', 'confirmed', 'fulfilled', 'paid', 'momo_paid', 'vnpay_paid'),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_cat_parent'), ['parent_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    op.create_table('shipping_rates',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ward', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_method', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('base_fee', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('per_kg_fee', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('free_shipping_threshold', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estimated_days_min', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estimated_days_max', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('inventory_transactions')
    op.drop_table('v_products_effective_price')
    op.drop_table('v_product_rating')
    # ### end Alembic commands ###
